[versions]
kotlin = "2.0.20"
compose = "1.7.0"
ads = "23.3.0"

[libraries]
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version = "1.7.0" }
ads-mobile-sdk = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "ads" }

[plugins]
android-application = { id = "com.android.application", version = "8.11.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
